[tool.poetry]
name = "spacecubes"
version = "0.3.3"
description = "Simple rendering of three-dimensional NumPy arrays"
authors = ["Johan Modin <johan.modin92@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/johanmodin/spacecubes"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.24"
pyquaternion = "^0.9.9"
opencv-python = { version = "^4.7", optional = true }


[tool.poetry.extras]
all = ["opencv-python"]
opencv = ["opencv-python"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
